apiVersion: v1
kind: Service
metadata:
  name: demo-service-microservice-bp
  namespace: demo
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: demo-microservice-bp