apiVersion: v1
kind: Service
metadata:
  name: staging-service-microservice-bp
  namespace: staging
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: staging-microservice-bp