apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: staging-deployment-microservice-bp
  namespace: staging
spec:
  replicas: 2
  revisionHistoryLimit: 5
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        environment: staging
        app: staging-microservice-bp
    spec:
      containers:
        - name: staging-microservice-bp
          image: jmeraq/microservice-bp:latesd
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 0.5Gi
            limits:
              cpu: "1"
              memory: 1Gi
          ports:
            - name: http-port
              containerPort: 80
          env:
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: staging-configmap-microservice-bp
                  key: environment
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: staging-secret-microservice-bp
                  key: api.key