pipeline {
    agent {
        docker { image 'jmeraq/tools:latest' }
    }
    stages {
        stage('Test') {
            steps {

                sh "cd iac/ && ls -la"
                sh "echo $PWD"
                sh "ls -la"
                sleep 600

                sh 'terraform init'
                sh 'terraform plan'
            }
        }
    }
}