pipeline {
    agent {
        docker { image 'jmeraq/tools:latest' }
    }
    stages {
        stage('Test') {
            steps {

                sh "cd /home/jenkins/"
                sh "echo $PWD"
                sleep 5
                sh "ls -la"
                sh 'terraform init'
                sh 'terraform plan'
            }
        }
    }
}